title: ""
description: "Main hub and digital laboratory hosting the creative worlds and research of Stella Boschi. Writing to live."
baseurl: "" 
url: "https://stellaboschi.io"

# Parametri per il Footer (Auto-aggiornante)
start_year: 2000
copyright_name: "Stella Boschi"
